[package]
name = "free-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "numeric", "uuidv07", "chrono"] }
actix-cors = "0.5.4"
dotenv = "0.15.0"
chrono = {version = "0.4.19", features = ["serde"]}
rand = "0.8.4"
# serde = "1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.59"
async-graphql = "3.0"
async-graphql-actix-web = "3.0"
bb8 = "0.7.1"
rust-argon2 = "1.0.0"
# uuid = "0.8.2"
uuid = { version= "0.8.2 ", features = ["serde", "v4"] } 
tracing = "0.1.29"