# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
# The following is essential for diesel-derive-enum
# custom_type_derives = ["diesel::query_builder::QueryId"]